import { SiHyundai, SiJeep, SiRenault } from "react-icons/si";

  export const carDonnees = [
  {
    id:1,
    value: "jeepRubiconwrangler",
    label: "Jeep Rubicon Wrangler ",
    imageUrl: "images/jeep.webp",
    marque: SiJeep ,
    modele: "Jeep Rubicon Wrangler ",
    annee: 2024,
    prix: 48000000,
    boiteVitesse: "Automatique",
    Carburant: "Essence",
    status : true,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas consequatur, cumque quisquam, voluptate deleniti corporis, doloremque magnam nisi ipsum dicta. Voluptas consequatur, cumque quisquam, voluptate deleniti corporis, doloremque magnam nisi ipsum dicta."
  },
  {
    id:2,
    value: "jeepRubicon",
    label: "Jeep Rubicon  ",
   imageUrl: "images/JeepV.webp",
    marque: SiJeep ,
    modele: " Jeep Rubicon ",
    annee: 2024,
    prix: 60000000,
    boiteVitesse: "Manuelle",
    Carburant: "Diesel",
    status : false,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas consequatur, cumque quisquam, voluptate deleniti corporis, doloremque magnam nisi ipsum dicta. Voluptas consequatur, cumque quisquam, voluptate deleniti corporis, doloremque magnam nisi ipsum dicta."
  },
  {
    id:3,
    value: "Jeepcompass",
    label: "Jeep Compass",
    imageUrl : "images/compass.webp",
    marque: SiJeep ,
    modele: " Jeep compass",
    annee: 2024,
    prix: 28900000,
    boiteVitesse: "Automatique",
    Carburant: "Essence",
    status : true,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas consequatur, cumque quisquam, voluptate deleniti corporis, doloremque magnam nisi ipsum dicta. Voluptas consequatur, cumque quisquam, voluptate deleniti corporis, doloremque magnam nisi ipsum dicta."
  },
    {
      id:4,
      value: "hyundaiTucson",
    label: "Hyundai Tucson",
    imageUrl : "images/hyundaiTucson.webp",
    marque: SiHyundai ,
    modele: "Hyundai Tucson",
    annee: 2017,
    prix: 69000000,
    boiteVitesse: "Manuelle",
    Carburant: "Diesel",
    status : false,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas consequatur, cumque quisquam, voluptate deleniti corporis, doloremque magnam nisi ipsum dicta. Voluptas consequatur, cumque quisquam, voluptate deleniti corporis, doloremque magnam nisi ipsum dicta."
  },
    {
      id:5,
      value: "RenaultSamsung",
    label: "Renault Samsung",
    imageUrl : "images/renault.webp",
    marque: SiRenault,
    modele: "Renault Samsung",
    annee: 2017,
    prix: 7500000,
    boiteVitesse: "Automatique",
    Carburant: "Essence",
    status : true,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas consequatur, cumque quisquam, voluptate deleniti corporis, doloremque magnam nisi ipsum dicta. Voluptas consequatur, cumque quisquam, voluptate deleniti corporis, doloremque magnam nisi ipsum dicta."
  },
    {id:6,
    value: "jeepcherokee",
    label: "Jeep Cherokee",
    imageUrl : "images/jeep.webp",
    marque: SiJeep,
    modele: "cherokee",
    annee: 2000,
    prix: 48000000,
    boiteVitesse: "Manuelle",
    Carburant: "Diesel",
    status : true,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas consequatur, cumque quisquam, voluptate deleniti corporis, doloremque magnam nisi ipsum dicta. Voluptas consequatur, cumque quisquam, voluptate deleniti corporis, doloremque magnam nisi ipsum dicta."
  },
];


//   export const carLocations = [
//   {
//     value: "jeepRubiconwrangler",
//     label: "Jeep Rubicon Wrangler",
//     imageUrl: "images/jeep.webp",
//     marque: SiJeep ,
//     modele: "Jeep Rubicon Wrangler ",
//     annee: 2024,
//     prix: 48000000,
//     typeLocation: "jour",
//     boiteVitesse: "Automatique",
//     Carburant: "Essence",
//     status : true,
//   },
//   {
//     value: "jeepRubicon",
//     label: "Jeep Rubicon  ",
//    imageUrl: "images/JeepV.webp",
//     marque: SiJeep ,
//     typeLocation: "mois",
//     modele: " Jeep Rubicon ",
//     annee: 2024,
//     prix: 60000000,
//     boiteVitesse: "Manuelle",
//     Carburant: "Diesel",
//     status : false,
//   },
//   {
//     value: "Jeepcompass",
//     label: "Jeep Compass",
//     imageUrl : "images/compass.webp",
//     marque: SiJeep ,
//     modele: " Jeep compass",
//     annee: 2024,
//     prix: 28900000,
//     boiteVitesse: "Automatique",
//     Carburant: "Essence",
//     status : true,
//   },
//     {
//       value: "hyundaiTucson",
//     label: "Hyundai Tucson",
//     imageUrl : "images/hyundaiTucson.webp",
//     marque: SiHyundai ,
//     modele: "Hyundai Tucson",
//     annee: 2017,
//     prix: 69000000,
//     boiteVitesse: "Manuelle",
//     Carburant: "Diesel",
//     status : false,
//   },
//     {
//       value: "RenaultSamsung",
//     label: "Renault Samsung",
//     imageUrl : "images/renault.webp",
//     marque: SiRenault,
//     modele: "Renault Samsung",
//     annee: 2017,
//     prix: 7500000,
//     boiteVitesse: "Automatique",
//     Carburant: "Essence",
//     status : true,
//   },
//     {
//       value: "jeepcherokee",
//     label: "Jeep Cherokee",
//     imageUrl : "images/jeep.webp",
//     marque: SiJeep,
//     modele: "cherokee",
//     annee: 2000,
//     prix: 48000000,
//     boiteVitesse: "Manuelle",
//     Carburant: "Diesel",
//     status : true,
//   },
// ];

 export const carLocations = [
  {
    imageUrl: "images/jeep.webp",
    marque: SiJeep,
    modele: "Jeep Rubicon Wrangler ",
    annee: 2024,
    prix: 20000,
    typeLocation: "jour",
    boiteVitesse: "Automatique",
    Carburant: "Essence",
    status: true,
    value: "jeepRubiconwrangler",
    label: "Jeep Rubicon Wrangler ",
  },
  {
   imageUrl: "images/JeepV.webp",
    marque: SiJeep,
    modele: " Jeep Rubicon ",
    annee: 2024,
    prix: 20000,
    typeLocation: "mois",
    boiteVitesse: "Manuelle",
    Carburant: "Diesel",
    status: false,
    value: "jeepRubicon",
    label: "Jeep Rubicon  ",
  },
  {
    imageUrl : "images/compass.webp",
    marque: SiJeep,
    modele: " Jeep compass",
    annee: 2024,
    prix: 25000,
    typeLocation: "jour",
    boiteVitesse: "Automatique",
    Carburant: "Essence",
     status: true,
    value: "Jeepcompass",
    label: "Jeep Compass",
  },
    {
    imageUrl : "images/hyundaiTucson.webp",
    marque: SiHyundai,
    modele: "Hyundai Tucson",
    annee: 2017,
    prix: 20000,
    typeLocation: "mois",
    boiteVitesse: "Manuelle",
    Carburant: "Diesel",
    status: true,
    value: "hyundaiTucson",
    label: "Hyundai Tucson",
   
  },
    {
    imageUrl : "images/renault.webp",
    marque: SiRenault,
    modele: "Renault Samsung",
    annee: 2017,
    prix: 20000,
    typeLocation: "jour",
    boiteVitesse: "Automatique",
    Carburant: "Essence",
    status: false,
    value: "RenaultSamsung",
    label: "Renault Samsung",
    
  },
    {
    imageUrl : "images/jeep.webp",
    marque: SiJeep,
    modele: "cherokee",
    annee: 2000,
    prix:20000,
    typeLocation: "mois",
    boiteVitesse: "Manuelle",
    Carburant: "Diesel",
    status: true,
    value: "jeepcherokee",
    label: "Jeep Cherokee",
   
  },
];


